Repository APRO-Project/bomberman, pull requests merged in 2020-06, with the labels that each got.

#13 Fix development branch
  client/core/src/com/cyberbot/bomberman/managers/GameScreenManager.java
  client/core/src/com/cyberbot/bomberman/screens/GameScreen.java
Labels: bug

#27 Player death handling
  .idea/misc.xml
  client/core/src/com/cyberbot/bomberman/screens/hud/GameHud.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/GameStateController.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/LocalWorldController.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/WorldChangeListener.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/Entity.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/PlayerEntity.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/Upgrade.java
  core/src/main/java/com/cyberbot/bomberman/core/utils/Constants.java
  core/src/main/java/com/cyberbot/bomberman/core/utils/Utils.java
  core/src/main/java/com/cyberbot/bomberman/core/utils/utils.kt
  server/src/main/kotlin/com/cyberbot/bomberman/server/control/ServerService.kt
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/GameSocket.kt
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/PlayerSession.kt
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/Session.kt
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/SessionService.kt
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/SessionStateListener.kt
Labels: bug, enhancement

#28 Item improvement
  .idea/dictionaries/krzys.xml
  client/core/src/com/cyberbot/bomberman/controllers/InputController.java
  client/core/src/com/cyberbot/bomberman/screens/hud/InventoryButton.java
  client/core/src/com/cyberbot/bomberman/screens/hud/InventoryView.java
  client/core/src/com/cyberbot/bomberman/sprites/BombSprite.java
  client/core/src/com/cyberbot/bomberman/sprites/SpriteFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/PlayerActionController.java
  core/src/main/java/com/cyberbot/bomberman/core/models/defs/BombDef.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/BombEntity.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/CollectibleFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/Inventory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/ItemStackFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/ItemType.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/RefilingItemStack.java
  core/src/main/java/com/cyberbot/bomberman/core/models/net/data/BombData.java
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/Session.kt
Labels: enhancement

#30 Code and documentation improvements
  .idea/misc.xml
  client/core/build.gradle
  client/core/src/com/cyberbot/bomberman/Client.java
  client/core/src/com/cyberbot/bomberman/controllers/NetworkedGameplayController.java
  client/core/src/com/cyberbot/bomberman/models/KeyBinds.java
  client/core/src/com/cyberbot/bomberman/screens/hud/PlayerListView.java
  client/core/src/com/cyberbot/bomberman/screens/lobby/LobbyLayout.java
  client/core/src/com/cyberbot/bomberman/screens/login/LoginScreen.java
  client/core/src/com/cyberbot/bomberman/screens/menu/MenuScreen.java
  client/core/src/com/cyberbot/bomberman/sprites/CollectibleSprite.java
  client/desktop/build.gradle
  core/build.gradle
  core/src/main/java/com/cyberbot/bomberman/core/controllers/GameStateController.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/LocalWorldController.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/PlayerActionController.java
  core/src/main/java/com/cyberbot/bomberman/core/models/PlayerState.java
  core/src/main/java/com/cyberbot/bomberman/core/models/actions/Action.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/PlayerEntity.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/ItemType.java
  core/src/main/java/com/cyberbot/bomberman/core/models/net/SerializationUtils.kt
  core/src/main/java/com/cyberbot/bomberman/core/models/tiles/PhysicalTile.java
  core/src/main/java/com/cyberbot/bomberman/core/models/tiles/TileMap.java
  server/build.gradle
  server/src/main/kotlin/com/cyberbot/bomberman/server/control/ClientControlService.kt
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/Session.kt
Labels: documentation

#34 Fix world simulation locks
  client/core/src/com/cyberbot/bomberman/controllers/NetworkedGameplayController.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/LocalWorldController.java
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/Session.kt
Labels: bug

#38 Fix some errors in PlayerListView
  client/core/src/com/cyberbot/bomberman/screens/hud/PlayerListView.java
Labels: bug, enhancement

#39 Minor fixes and improvements
  build.gradle
  client/core/src/com/cyberbot/bomberman/controllers/ScreenController.java
  client/core/src/com/cyberbot/bomberman/screens/finish/FinishLayout.java
  client/core/src/com/cyberbot/bomberman/screens/login/LoginLayout.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/GameStateController.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/PlayerActionController.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/CollectibleFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/PlayerEntity.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/ItemStackFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/utils/Utils.java
  server/src/main/kotlin/com/cyberbot/bomberman/server/control/ServerService.kt
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/Session.kt
Labels: bug, enhancement

#44 Add freezer upgrade
  client/core/assets/textures/bomberman.atlas
  client/core/assets/textures/bomberman.png
  client/core/src/com/cyberbot/bomberman/controllers/NetworkedGameplayController.java
  client/core/src/com/cyberbot/bomberman/sprites/GraphicsFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/GameStateController.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/LocalWorldController.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/PlayerActionController.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/CollectibleFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/PlayerEntity.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/Inventory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/ItemStackFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/ItemType.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/Upgrade.java
  core/src/main/java/com/cyberbot/bomberman/core/models/net/data/PlayerData.java
  server/src/main/kotlin/com/cyberbot/bomberman/server/session/Session.kt
Labels: enhancement

#46 Minor inventory and inventory view changes
  client/core/src/com/cyberbot/bomberman/screens/hud/InventoryView.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/Inventory.java
Labels: enhancement

#47 Add insta boom upgrade
  .idea/dictionaries/bruteus.xml
  build.gradle
  client/core/assets/Icon.png
  client/core/assets/Texture_Pack.png
  client/core/src/com/cyberbot/bomberman/screens/hud/InventoryView.java
  client/core/src/com/cyberbot/bomberman/sprites/GraphicsFactory.java
  client/desktop/src/com/cyberbot/bomberman/DesktopLauncher.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/GameStateController.java
  core/src/main/java/com/cyberbot/bomberman/core/controllers/PlayerActionController.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/BombEntity.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/CollectibleFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/entities/ExplosionEntity.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/Inventory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/ItemStackFactory.java
  core/src/main/java/com/cyberbot/bomberman/core/models/items/ItemType.java
Labels: enhancement
